import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "StockGPT-Your AI Powered Stock Assistant",
  description: "Generated by create next app",
  
};
const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200','400','600','800'],
  variable: '--font-sans'
});


export default function RootLayout({ children }) {
  return (
     <html lang="en" className={plusJakarta.variable}>
      <body className="antialiased font-sans">
        {children}
      </body>
    </html>
  );
}
